using UnityEngine;
using UnityEditor;
using Miscreant.Aseprite.Editor;
using System.IO;

/// <summary>
/// Automatically adds sprite data to packed atlases generated by importing Aseprite files
/// </summary>
class AsepriteAtlasPostprocessor : AssetPostprocessor // TODO: Miscreant: Move this to a precompiled .dll to prevent modification once it's stable
{
	void OnPreprocessTexture()
	{
		if (assetPath.Contains(AsepriteImporter.ATLAS_SUFFIX))
		{
			// Check for associated JSON data, must be in the same folder.
			string dataAssetPath = assetPath.Substring(0, assetPath.LastIndexOf(AsepriteImporter.ATLAS_SUFFIX)) + $"{AsepriteImporter.ATLAS_SUFFIX}.json";

			// Load the sheet data via File IO since there's a chance Unity may not have imported it as an asset yet
			string projectPath = Application.dataPath.Substring(0, Application.dataPath.LastIndexOf("/Assets"));
			string dataAbsolutePath = projectPath + "/" + dataAssetPath;

			var sheetData = JsonUtility.FromJson<SpriteSheetData>(File.ReadAllText(dataAbsolutePath));

			AsepriteImporter.UpdatePackedSprites((TextureImporter)assetImporter, sheetData);
		}
	}
}